
[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "forge-std/=lib/forge-std/src/",
    "v4-core/=lib/v4-core/src/",
    "v4-periphery/=lib/v4-periphery/src/"
]

[profile.default.optimizer]
enabled = true
runs = 200

[profile.default.model_checker]
contracts = {}
engine = 'chc'
timeout = 10000

[rpc_endpoints]
zora_testnet = "https://sepolia.rpc.zora.energy"
